### ISSUE TITLE
Reinstallation of German Locale Pack

### ISSUE THREAD

**Issue by dfsdouglas** [riconeitzel/German_LocalePack_de_DE#113]
Hallo Herr Neitzel,

Ich habe heute das German Localepack installiert und hatte das Problem dass Ordner anstatt der CSV Datein angelegt wurden oder bestimmte Ordner leer waren. 

Daraufhin habe ich ihre Anweisung befolgt:
"Treten bei Ihnen diese Probleme auf, deinstallieren Sie das Sprachpaket im Magento Connect Manager, löschen Sie bitte anschließend folgende Ordner sofern sie vorhanden sind: /app/design/adminhtml/default/default/locale/de_DE/translate.csv, /app/design/adminhtml/default/default/layout/localepackede.xml, app/design/frontend/default/default/locale/de_DE/translate.csv, /app/design/adminhtml/base/default/locale/de_DE/translate.csv, /app/design/adminhtml/base/default/layout/localepackede.xml, app/design/frontend/base/default/locale/de_DE/translate.csv und installieren Sie das Sprachpaket erneut."

Die Ordner sind nicht mehr vorhanden, jedoch beim erneuten Versuch die Extension über Magento Connect zu installieren bekomme ich folgenden Fehler:

"Checking dependencies of packages

CONNECT ERROR: Package 'Locale_Mage_community_de_DE' is invalid
'./app/design/frontend/default/default/locale/de_DE/translate.csv' already exists"

In dem Ordner existiert aber nur der en_US Ordner. 

Was mache ich hier falsch?

Vielen Dank.
David

**Comment by yourstool** [comment]
Rico,

I seem to have the same problem now. I did install through connect and can't find the files mentioned in the previous post. The other language file was not installed in my `1.9. version. Can you help?

**Comment by riconeitzel** [comment]
What exactly is the error message?

**Comment by yourstool** [comment]
a:5:{i:0;s:67:"Mage registry key "_singleton/localepackde/observer" already exists";i:1;s:1422:"#0 /var/www/vhosts/yourstool.nl/httpdocs/app/Mage.php(223): Mage::throwException('Mage registry k...')

**Comment by riconeitzel** [comment]
Ahaaaaa - very different thing. Will look into it.

**Comment by yourstool** [comment]
Should I open a new line for this then?

**Comment by riconeitzel** [comment]
If you like - yes. It's a different error
