### ISSUE TITLE
could not install via composer

### ISSUE THREAD

**Issue by roman204** [riconeitzel/German_LocalePack_de_DE#160]
When i try to install via composer the following error message occours:
vendor/riconeitzel/german-localepack-de-de/app/design/frontend/rwd/default/locale/de_DE/translate.csv does not exist

i'm on branch master in my composer.json

edit:
in modman file line 37 is the instruction

**Comment by riconeitzel** [comment]
the modman file is not yet updated … so it's still in progress an fully outdated (the modman file).

Best,
 Rico
