### ISSUE TITLE
Notice: Undefined index: files 

### ISSUE THREAD

**Issue by gaiterjones** [riconeitzel/German_LocalePack_de_DE#170]
Notice: Undefined index: files  in app/code/core/Mage/Core/Model/Translate.php on line 138

When I enable this module in development mode I get the above exception error when trying to access the admin backend.

Magento 1.9.1 CE

**Comment by Schrank** [comment]
I can't reproduce this problem. Which version from the module are you using?

**Comment by Schrank** [comment]
But what might help:
Your error says, that the module doesn't have a files nodes I would say.

**Comment by gaiterjones** [comment]
Thanks for the reply, I had installed the module via Magento connect (Locale_Mage_community_de_DE). Installing the latest version from the github resolved the problem.
