### ISSUE TITLE
translate.csv in blank theme is missing, no composer install possible

### ISSUE THREAD

**Issue by michaeltimm81** [riconeitzel/German_LocalePack_de_DE#171]
When trying to install or update via composer an exception is thrown:

```
[ErrorException]                                                                                                                                                          
  Source ...../vendor/connect20/Locale_Mage_community_de_DE/./app/design/frontend/default/blank/locale/de_DE/translate.csv does not exists
```

This is quite a big thing for us since we cannot do a composer update to our shops anymore without fully breaking it or at least losing the german translation.

Hope you get it fixed soon, thanks

**Comment by Schrank** [comment]
Did you try to use riconeitzel/german-localepack-de-de instead of the connect packages?

**Comment by michaeltimm81** [comment]
No, I thought they were the same...
But I will try it with this one until the connect20 package is back up again. 
Thank you
