### ISSUE TITLE
Checkout: "Nevermind, ship to my billing address instead" nicht übersetzt

### ISSUE THREAD

**Issue by mklooss** [riconeitzel/German_LocalePack_de_DE#172]
"Nevermind, ship to my billing address instead","An Rechnungsadresse versenden"

**Comment by riconeitzel** [comment]
wie bitte?! :D

**Comment by winkelsdorf** [comment]
Und ich such wirklich danach.. ;)

Bitte auch adden:
"I have no Money but want to order anyway", "Ich bin zwar pleite, möchte aber trotzdem bestellen"

**Comment by mklooss** [comment]
war als Reminder gedacht, aber sehe gerade, dass muss in 3 Projekten so hinterlegt wurden sein,
da Magento den Text: "Use Billing Address" verwendet.

**Comment by riconeitzel** [comment]
Also können wir das schließen? :D

**Comment by mklooss** [comment]
Nevermind, jaaa :D

**Comment by winkelsdorf** [comment]
Ihr habt wohl Spaß.. Glaub ich wechsel auch permanent in die Magento Community ;)

**Comment by riconeitzel** [comment]
Spaß sowieso :D anders ist das gar nicht auszuhalten 😂

**Comment by winkelsdorf** [comment]
Das stimmt, tat mal gut 😂
