### ISSUE TITLE
Falsche Übersetzung bei Passwort-Validierung

### ISSUE THREAD

**Issue by mash1t** [riconeitzel/German_LocalePack_de_DE#173]
Aufgefallen beim Erstellen eines Kunden:
"Please make sure your passwords match.","Bitte stellen Sie sicher, dass die beiden Passworte identisch sind."
=> müsste "Please make sure your passwords match.","Bitte stellen Sie sicher, dass die beiden Passwörter identisch sind." heißen

**Comment by winkelsdorf** [comment]
Danke, gefixt! Ich mache gleich einen Pull Request für Rico.

https://github.com/winkelsdorf/German_LocalePack_de_DE/commit/8a3262ff17a756076a622ee524834738147cdd5d
