### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by infabo** [riconeitzel/German_LocalePack_de_DE#176]
code/core/Mage/Customer/controllers/AccountController.php:

$message = $this->_getHelper('customer')->__('This account is not confirmed. <a href="%s">Click here</a> to resend confirmation email.', $value);

code/core/Mage/Customer/Model/Customer.php:

throw Mage::exception('Mage_Core', Mage::helper('customer')->__('This account is not confirmed.')

**Comment by winkelsdorf** [comment]
'This account is not confirmed' sehe ich in Mage_Customers.csv im Preview übersetzt.

Meinst Du "Account confirmation is required. Please, check your e-mail for confirmation link. To resend confirmation email please <a href=""%s"">click here</a>."?

**Comment by winkelsdorf** [comment]
Danke, gefixt und im PR für Rico!
