### ISSUE TITLE
Bestellstati im Adminbereich

### ISSUE THREAD

**Issue by R3dRuM** [riconeitzel/German_LocalePack_de_DE#179]
Mage_Sales.csv 

"Order Statuses","Bestellstati &amp; -zustände"

Der Plural von Status lautet nicht etwa „Stati“, sondern wie der Nominativ und der Genitiv Singular: Status. Im Genitiv und im Plural wird allerdings das u lang ausgesprochen.

http://www.korrekturen.de/beliebte_fehler/stati.shtml

**Comment by riconeitzel** [comment]
Die Diskussion wurde schon des öfteren angeregt und ist bekannt. Im Zuge des allgemeinen Sprachgebrauchs und besseren Verständnisses wurde aber zu Gunsten des falschen Plurals entschieden.

**Comment by dakira** [comment]
> Im Zuge des allgemeinen Sprachgebrauchs

Also uns ist das zum ersten mal in der falschen Übersetzung in Magento untergekommen. Nach dem ich das seit einer gefühlten Ewigkeit für Kunden anpasse, die mich darauf ansprechen, dachte ich, ich mach endlich mal nen Pull Request. Aber gut, so wichtig ist es nun auch wieder nicht. ;)
