### ISSUE TITLE
Installation Locale_Mage_community_de_DE

### ISSUE THREAD

**Issue by frudolf13** [riconeitzel/German_LocalePack_de_DE#183]
Hallo,
ich habe eine CE ver 1.9.1.0 neu installiert. Auch das Sprachpaket, wurde über Magento connect installiert (wird im channel als Locale_Mage_community_de_DE -	1.9.1.0.1 (stable) aufgelistet.
Nur ich sehe weder im Frontend noch im Backend eine deutsche Übersetzung...
Was mache ich falsch?
Beste Grüße!

**Comment by frudolf13** [comment]
... hat sich von selbst gelöst - im Backend muss mann zwingend Deutsch (Deutschland) auswählen und nicht Deutsch (Österreich). das selbe beim Frontend.
Vielen Dank trotzdem.

**Comment by Schrank** [comment]
de_DE ist deutsche Sprache in Deutschland. Du kannst auch ein österreichisches Paket (de_AT) oder schweizer Paket (de_CH) installieren :)

**Comment by Sabay1** [comment]
Hallo,

ich habe bin neu hier und versuche meinen ersten Magento-Shop (Version 1.9.1.1) aufzusetzen.

Ich habe mich sehr gefreut über das German_LocalePack_de_DE und gleich installiert. Versehentlich habe ich vergessen den Ordner auf dem Server umumbenennen in magento_de_DE.

Jetzt kann ich das Sprachpaket nicht mehr deinstallieren sowie refreshen. Hast jemand einen Lösungsvorschlag für mich?

Ich freue mich sehr über jede Antwort!

Beste Grüße

**Comment by riconeitzel** [comment]
Hallo, ich muss leider gestehen, dass ich nicht verstehe, warum du genau den Ordner umbenennen wolltest … ? Was möchtest Du denn jetzt machen und was funktioniert nicht und welche Fehlermeldung entsteht dabei?
Viele Grüße
 Rico

**Comment by Sabay1** [comment]
Hallo Rico,

ich habe keinerlei Fehlermeldung jedoch funktioniert German_LocalePack_de_DE nicht. Daher wollte ich es deinstaiieren und neu installieren. Die deinstallation funktioniert jedoch nicht (siehe Datei).

Vielen Dank für deine rasche Antwort!!!

Beste Grüße
André
![connect](https://cloud.githubusercontent.com/assets/12910271/8181652/158305c6-1428-11e5-841b-8d6c6f979dbf.PNG)

**Comment by riconeitzel** [comment]
Kannst Du mal prüfen bitte, ob app/design/frontend/default/blank/locale/de_DE/translate.csv überhaupt existiert? Ich denke, dass Du diese Ordner gelöscht hast und er deswegen dort aussteigt.

**Comment by Sabay1** [comment]
Der Ordner besteht ist jedoch leer.
![1](https://cloud.githubusercontent.com/assets/12910271/8181705/a9a716b6-1428-11e5-8425-dcdc0c989c03.PNG)

**Comment by riconeitzel** [comment]
das ist das alte problem … translate.csv müsste eine Datei sein, aber auf deinem Rechner ist es ein Ordner. Das ist auf der Projektseite beschrieben. Bitte folge diesen Anweisungen: 

Sollte das Sprachpaket nicht wie gewohnt funktionieren, bitte Caches löschen und neu einloggen. Geht es danach immernoch nicht, bitte das Sprachpaket nochmal deinstallieren und wieder neu installieren.

Fehler in Version 1.7.0.x Seit 1.7.0.2.3 ist ein Fehler behoben, der beim Konvertieren des Connect 1.0 in einer 2.0 Paket entstanden ist. Dabei wurden einige Dateien nicht korrekt als Datei entpackt sondern als leere Ordner angelegt, die den Dateinamen als Ordnernamen tragen.

Bei einem Update der Extension wird dies zwangsläufig zur Problemen kommen, da diese defekten Ordner nicht gelöscht werden, eine Datei mit dem gleichen Namen aber nicht daneben gelegt werden darf.

Treten bei Ihnen diese Probleme auf, deinstallieren Sie das Sprachpaket im Magento Connect Manager, löschen Sie bitte anschließend folgende Ordner sofern sie vorhanden sind: 

* /app/design/adminhtml/default/default/locale/de_DE/translate.csv, 
* /app/design/adminhtml/default/default/layout/localepackede.xml, 
* app/design/frontend/default/default/locale/de_DE/translate.csv, 
* /app/design/adminhtml/base/default/locale/de_DE/translate.csv,  
* /app/design/adminhtml/base/default/layout/localepackede.xml, 
* app/design/frontend/base/default/locale/de_DE/translate.csv 

und installieren Sie das Sprachpaket erneut.

Du hast Windows … Windows vergeigt es leider manchmal beim Entpacken.

**Comment by riconeitzel** [comment]
Und dann löschst Du alle Ordner, die in dem schwarzen Fenster mit dem grünen Text NOCH auftauchen.

**Comment by Sabay1** [comment]
Ok - vielen Dank!
Die caches vom Browser oder von Magento löchen? 

Treten bei Ihnen diese Probleme auf, deinstallieren Sie das Sprachpaket im Magento Connect Manager, löschen Sie bitte anschließend folgende Ordner sofern sie vorhanden sind:

    /app/design/adminhtml/default/default/locale/de_DE/translate.csv,
    /app/design/adminhtml/default/default/layout/localepackede.xml,
    app/design/frontend/default/default/locale/de_DE/translate.csv,
    /app/design/adminhtml/base/default/locale/de_DE/translate.csv,
    /app/design/adminhtml/base/default/layout/localepackede.xml,
    app/design/frontend/base/default/locale/de_DE/translate.csv

und installieren Sie das Sprachpaket erneut.
Ich kann ja leider nicht das Sprachpaket im Magento Connect Manager löschen.

**Comment by riconeitzel** [comment]
"Ich kann ja leider nicht das Sprachpaket im Magento Connect Manager löschen" siehe vorheriger Kommentar. Alles löschen, was da noch drin steht.

Caches: Magento

**Comment by Sabay1** [comment]
Sorry - leider verstehe ich nicht "Und dann löschst Du alle Ordner, die in dem schwarzen Fenster mit dem grünen Text NOCH auftauchen." ?

So sieht jetzt mein cache aus:
![2](https://cloud.githubusercontent.com/assets/12910271/8182062/c8601afa-142b-11e5-88ce-d4ac99b23152.PNG)

**Comment by Sabay1** [comment]
Perfekt ich habe es geschafft ;-)
Vielen lieben Dank Rico!!!!
