### ISSUE TITLE
„Please type the letters below“ wird nicht übersetzt

### ISSUE THREAD

**Issue by raubv0gel** [riconeitzel/German_LocalePack_de_DE#191]
„Please type the letters below“ wird nicht übersetzt, obwohl es in /var/www/magento/app/locale/de_DE/Mage_Captcha.csv enthalten ist. Siehe auch:

![issue](https://cloud.githubusercontent.com/assets/9824146/8110648/b226e22c-105d-11e5-88ec-3a5fec2e9c03.png)

**Comment by MaWoScha** [comment]
Die Übersetzung hier einstellen:
app/design/frontend/rwd/default/locale/de_DE/translate.csv
oder hier:
app/design/frontend/default/default/locale/de_DE/translate.csv
