### ISSUE TITLE
Sale label = Verkauf

### ISSUE THREAD

**Issue by Sabay1** [riconeitzel/German_LocalePack_de_DE#193]
Hallo,

wenn ich ein Produkt mit dem Sale label versehe, dann wird im Frontend "Verkauf" angezeigt.
Kann man das wieder in bspw. "Sale" ändern?

Ich freue mich sehr über eine Antwort.

Beste Grüße
André

**Comment by riconeitzel** [comment]
Hallo André,

In deinem Theme legst du eine translate.csv in locale/de_DE und schreibst da

```
"Sale","Sale"
```

rein.

Viele Grüße Rico

**Comment by Sabay1** [comment]
Hallo Rico,

vielen Dankl für deine Antwort.

Ich habe die Datei in App/locale/de_DE gelegt kann aber keine Änderung feststellen.

Hast du eine Idee was ich falsch gemacht habe?

Schöne Grüße
André

**Comment by riconeitzel** [comment]
Ja, die muss in dein Theme. 😊

**Comment by Sabay1** [comment]
ok ich habes es (denke ich mal) gefunden: /public_html/app/design/frontend/default/theme654/locale/de_DE
dort was die translate.csv schon vorhanden und ich habe diese dann geändert jedoch bleibt der "Sticker" auf Verkauf

falls du noch eine Idee hast, dann wäre ich dir sehr dankbar

**Comment by riconeitzel** [comment]
Schau doch mal in deinem Theme “theme654” nach, welcher Text da tatsächlich für “Verkauf” verwendet wird. Vielleicht steht da noch was anderes dabei. Die CSV Datei muss exakt den Inhalt haben, wie auch der eigentliche Texte.

Viele Grüße
 Rico

**Comment by Sabay1** [comment]
der Quelltext lautet span class="sale">Verkauf</span>

Schöne Grüße und ein schönes Wochenende!!!!
André

**Comment by riconeitzel** [comment]
Hallo André,

nicht den gerenderten sondern den aus der PHTML Datei.

Viele Grüße
 Rico

**Comment by Sabay1** [comment]
Hi Rico,

ich denke, dass ich die richtige Datei gefunden haben und der code lautet:
<?php if($_product->getData('sale')){echo '<span class="sale">'.$this->__('Sale').'</span>';  }?>
Aber der Befehl "Sale","Sale" funktioniert in der schon vorhandenen translate.csv nicht. 

Ist das der code nach dem ich suche?

Beste Grüße
André

**Comment by riconeitzel** [comment]
Hallo André,

> ich denke, dass ich die richtige Datei gefunden haben und der code lautet:
> <?php if($product->getData('sale')){echo ''.$this->_('Sale').''; }?>

wie lautet denn der PFAD zu dieser Datei?

Viele Grüße
 Rico

**Comment by Sabay1** [comment]
app\design\frontend\default\theme654\template\catalog\product\new.phtml

**Comment by riconeitzel** [comment]
Na da haben wir's doch schon …

```
$this->__('Sale')
```

muss es heißen. 2x Unterstrich, nicht 1x.

**Comment by Sabay1** [comment]
Hallo Rico,

ich möchte mich rechtherzlich bei dir bedanken.

Beim Code hier im Forum einfügen ist mir ein Fehler unterlaufen und daher fehlte der Unterstrich. Danach kam ich mir so doof vor, so dass ich die Sache erstmal auf sich beruhen habe lasse ;-)

Heute Morgen wollte ich es dann nochmal wissen und ehrlichgesagt war dein erster Ansatz richtig. Ich weiß selbst nicht wieso es jetzt funktioniert jedoch ist mein Code so wie du schon sagtest: 
"Sale","Sonderangebot"!

Ich wünsche ein schönes Wochenende
André
