### ISSUE TITLE
eMail Templates funktionieren nicht

### ISSUE THREAD

**Issue by skenic2003** [riconeitzel/German_LocalePack_de_DE#219]
Hallo,
ich brauche einmal eure Hilfe!
Ich habe einen Magento Shop von v. 1.4.1.1 auf 1.9.2.2 geupdated und habe jetzt einige Probleme mit den Mail Templates. Ich habe schon die Extension gelöscht und auch die durch das Update fehlerhaft erstellten Ordner gelöscht und das Sprachpaket erneut installiert.
Leider habe ich aber immer noch die alten Mail-Templates, in welchen bei Betreff z.B. steht:
{{block type="germany/impressum" value="shopname"}}: Bestellung Nr. # {{var order.increment_id}}

Alle diese Blöcke sind allerdings leer. Wie bekomme ich die aktuellen Mail-Templates?

**Comment by riconeitzel** [comment]
Hallo!

WO hast Du diese Templates denn? Unter System -> Transaktionsmails?

Viele Grüße
 Rico

**Comment by skenic2003** [comment]
Genau, unter System -> Transaktionsmails.

**Comment by Schrank** [comment]
Das ist ein Problem mit 1.9.2.2 und die templates sind vermutlich von MarketReady Germany.

Du musst sie whitelisten: http://www.dudesquare.nl/blog/2015/10/31/static-block-shortcodes-not-working-1-9-2-2/

**Comment by riconeitzel** [comment]
naja, wenn du die aus app/locale/de_DE/email nutzen willst, darf unter system -> transaktionsmails nichts stehen

**Comment by Schrank** [comment]
Stimmt, aber wenn die Blöcke leer sind, ist es egal welche Mails du nimmst, das liegt am Whitelisting. Wenn man allerdings die Mails aus der DB löscht, werden die Templates aus dem Dateisystem benutzt, die sollten gewhitelistet sein - da hast du recht.

**Comment by skenic2003** [comment]
Danke euch! Hab das Problem jetzt an anderer Stelle gefunden. Ich wusste nicht, dass der Bereich im Admininterface leer sein muss, damit die Templates aus dem Verzeichnis genommen werden.

Mein Problem liegt allerdings daran, falls jemand anders mal in der selben Situation sein sollte:

In der alten Version war TechDivision_Germany installiert, welches diesen Block per PHP erzeugt hat. Das Modul ist allerdings sowas von veraltet, dass es nur bis v. 1.4 funktioniert. Muss jetzt also die Templates anpassen.

Vielen Dank auf jeden Fall für den superschnellen Support! :)
