### ISSUE TITLE
Magento 2

### ISSUE THREAD

**Issue by nickweisser** [riconeitzel/German_LocalePack_de_DE#228]
Aktuell steht die deutsche Übersetzung auf https://crowdin.com/project/magento-2 bei 28%. Gibt es bereits irgendwelche Pläne die in einem Community Effort zeitnah auf 100% zu bringen, damit deutschsprachige Händler ernsthaft Magento 2 in Erwägung ziehen können?

**Comment by riconeitzel** [comment]
Ich arbeite fieberhaft an der Mage1 Vollübersetzung, die dann auch für Mage2 herangezogen werden kann. Aktuell bin ich unglücklich mit der ALLES-IN-EINER-DATEI-Regel von Mage2 … :-/ ich würde gerne direkt in die Module rein, aber das wird wohl nichts.

**Comment by nickweisser** [comment]
Danke für die Antwort. Ich würde mich gerne mit ein paar Leuten von Openstream einbringen, um die Magento 2 Übersetzung voran zu treiben. Wir könnten z.B. intern eine Art Übersetzer-Hackathon durchführen, müssten aber wissen wie wir vorgehen sollen, damit alle einen nachhaltigen Nutzen davon haben.

**Comment by nnpro** [comment]
Hi Leute, ich würde mich auch dem Hackathon zur Übersetzung anschließen wollen mit 2 mageSHOPS.com Mitarbeitern. Haltet mich bitte am Laufenden

**Comment by splendidinternet** [comment]
für Magento 2 hatten wir losgearbeitet, weil wir die Übersetzung aktuell brauchen 
https://github.com/splendidinternet/Magento2_German_LocalePack_de_DE

beim Hackathon am letzten Wochenende in Paderborn 
https://www.splendid-internet.de/blog/firegento-magento-2-hackathon-paderborn-2016-mhpad16
haben wir dann noch die zu übersetzenden Teile rausgezogen, die über Javascript ausgeliefert werden und Workarounds für die Bugs in Magento 2 gefunden. Diese Woche wird noch übersetzt und nächste Woche wäre dann alles komplett.

**Comment by MaWoScha** [comment]
Ich habe selbst viel Zeit in die Übersetzung des Sprachpakets ins Spanische gesteckt - im Dezember war ich auf der ersten Magento-Konferenz in Buenos Aires - und mich gewundert, dass es bezüglich Magento 2 nichts über Sprachpakete zu hören gab. Hier lese ich zum ersten mal darüber und irgendwie scheint das noch gar nicht gar zu sein:
Wie kann man Magento 2 ausliefern, ohne dass Sprachpakete funktionieren?!?? Geht man davon aus, dass die meisten eh mit Englisch arbeiten und das nicht wichtig ist? Ich finde das seltsam.
Dann habe ich mir das Git-Projekt mit der Übersetzung für Magento 2 heruntergeladen und mir die CSV-Datei angesehen: Da finde ich viele "#NAME?" drin, uups, was ist denn das?
Und dann 6500 Einträge in einer(!) Datei. Also, ich hatte ja schon Schwierigkeiten mit der Übersetzung der Version 1.7-1.9, aber jetzt hat man 6500 Sprachschnipsel, ohne Anhaltspunkt in welchem Zusammenhang die stehen, wo die im System auftauchen ... wie kann man da sinnvoller Weise an die Übersetzung herangehen?
Der erste Eindruck lässt mich ratlos zurück...

**Comment by splendidinternet** [comment]
#Name? erscheint im Frontend, wenn nichts in der Zelle ist, also nicht mal das Original in Englisch.
Das betrifft vor allem die Phrasen, die über Javascript ausgeliefert werden und wir überarbeiten es gerade und können es voraussichtlich nächste Woche auf github livestellen. 
Unterstützung ist natürlich immer willkommen.

**Comment by MaWoScha** [comment]
"#Name?" steht IN DER CSV-DATEI. "Nichts in der Zelle" hieße nach meinem Verständnis, da stünde: ""

Und bei 6500 Sprachschnipseln, ohne Anhaltspunkt auf den Zusammenhang, also da wüsste ich nicht, wie ich da sinnvoll unterstützen könnte. Sisiphus-Arbeit wäre da im Vergleich wohl einfacher.

Ich habe die letzten Tage das LocalPack
https://github.com/riconeitzel/German_LocalePack_de_DE
überarbeitet und ich muss schon sagen, da waren einige Falschübersetzungen drin und die Tipp- und Schreibfehler gar nicht zu zählen. Man mag gar nicht glauben, dass sowas in den Produktiv-Einsatz geht.

Siehe die Korrekturen in
https://github.com/MaWoScha/German_LocalePack_de_DE
ab Version 0.4.4 bis 0.5.0

**Comment by MaWoScha** [comment]
Eine kleine Statistik zu
https://github.com/MaWoScha/German_LocalePack_de_DE
Ich habe 10187 Einträge, davon 1915 geändert (davon 149 neu) gezählt.
Also haben rund 1,5% der Einträge gänzlich gefehlt und 1/5 musste überarbeitet werden. Das reichte von fehlenden Punkten und Kommata über Tippfehler, Buchstabendreher, C&P-Fehler bis hin zu Falschübersetzungen. Für Produktivumgebungen würde ich mir ein professionelleres Sprachpaket wünschen...

**Comment by Schrank** [comment]
@MaWoScha Ich verstehe nicht, was das mit dem Issue zu tun hat?

**Comment by MaWoScha** [comment]
Ich bin davon ausgegangen, dass es hier darum geht, eine Übersetzung von Magento zu erstellen?!??

**Comment by MaWoScha** [comment]
Also ich habe mir gerade von Crowdin die Dateien (deutsch, spanisch) runtergeladen und stelle fest, dass in den Dateien ein Haufen Schrott drinsteht. Ich frage mich, was das soll?
Die offene Frage ist auch, wie man das über 6000 Einträge in angemessener Zeit darin eingestellt kriegt...

**Comment by MaWoScha** [comment]
Nur mal nebenbei bemerkt: Es stellt sich die Frage, wie lange es GitHub noch geben wird. Lest selbst:

Gender ruiniert die nächste Firma: GitHub
http://www.danisch.de/blog/2016/02/08/gender-ruiniert-die-nachste-firma-github/
Ansichten eines Informatikers

**Comment by avstudnitz** [comment]
Danke fürs Löschen des letzten Kommentars.

**Comment by nickweisser** [comment]
Ich habe basierend auf der Übersetzung von Splendid eine Abwandlung für de_CH erstellt, läuft aber noch nicht ganz rund. Würde ich mir spätestens beim nächsten Kundenprojekt oder Magento Hackathon detaillierter anschauen. Falls jemand spontan das Bedürfnis hat zu helfen, hier [zwei Issues](https://github.com/openstream/Magento2_German_LocalePack_de_CH/issues) ;-)
