### ISSUE TITLE
compatibility for php7

### ISSUE THREAD

**Issue by jsnx** [riconeitzel/German_LocalePack_de_DE#230]
Is there any chance to make this compatible with php7 ? My magento 1.9.2.4. runs fine with php7 but Im not abled to install this package.

**Comment by riconeitzel** [comment]
Hey there,

which error messages occur?

Rico

**Comment by jsnx** [comment]
Hey Rico,

wenn ich via Magento Connect das Package installieren möchte, schlägt gleich als zweites der php versions check fehl.

**Comment by Schrank** [comment]
Workaround: Installier es direkt, connect ist mist.

**Comment by riconeitzel** [comment]
Hi,

okay, yeah … the problem is the package built for magento connect … let's see if I can provide the revamped 1.9 till meet magento. there I'll change the requirements for php as well :)

Thanks!

**Comment by riconeitzel** [comment]
wird im nächsten tgz mit php 8.0.0 markiert
