### ISSUE TITLE
Minor issue: some .DS_Store files in tarball

### ISSUE THREAD

**Issue by hmb** [riconeitzel/German_LocalePack_de_DE#231]
./app/code/community/German/LocalePackDe/.DS_Store
./app/code/community/German/LocalePackDe/Model/.DS_Store
./app/code/community/German/LocalePackDe/etc/.DS_Store

**Comment by sprankhub** [comment]
I think this issue is fixed. I cannot see any `.DS_Store` files. If there still are some, please clarify where exactly @hmb.

**Comment by hmb** [comment]
Yep they seem to be gone. I close the issue.
