### ISSUE TITLE
"Purchase Order" eigene Übersetzung

### ISSUE THREAD

**Issue by KaiBroenstrup** [riconeitzel/German_LocalePack_de_DE#234]
Hi,
ich muss die Übersetzungen anpassen bekomme es aber in meinem Theme mit einem einfachen 
"Mage_Payment::Purchase Order Number","Zahlung mit" oder "Purchase Order Number","Zahlung mit" nicht hin. Er zieht immer die Mage_Payment aus dem localpack Ordner vor.

Was mache ich falsch?

**Comment by riconeitzel** [comment]
Hallo @KaiBroenstrup,

in welcher Datei stehen diese Strings? Die müssten in deinem Theme in der translate.csv im jeweiligen Sprachordner unter /locales/xx_XX/translate.csv liegen!

Viele Grüße
 Rico

**Comment by KaiBroenstrup** [comment]
Hi,

ja da sind Sie auch. Alle anderen Translations in der Datei werden auch korrekt genommen..

Grüße

**Comment by riconeitzel** [comment]
In welchem Template steht denn der Text, kopiere mal bitte den Code hier rein!

**Comment by riconeitzel** [comment]
Aaaaach - moment - geht's hier evt. um Texte aus dem System -> Konfig Adminbereich? Die musst du nämlich DORT übersetzen und für die jeweilige StoreView speichern!
