### ISSUE TITLE
Standardübersetzung überschreiben?

### ISSUE THREAD

**Issue by zlep** [riconeitzel/German_LocalePack_de_DE#241]
Hallo,

ich versuche zur Zeit die Standardübersetzung von "Select a billing address from your address book or enter a new address." durch meine eigene translate.csv zu überschreiben. Sieht so aus:

"Select a billing address from your address book or enter a new address.","Wählen Sie eine Rechungsadresse aus Ihrem Adressbuch."

Leider klappt das in diesem Fall nicht. Andere Übersetzungen habe ich bereits erfolgreich überschrieben.
Hat jemand einen Tipp, warum das nicht klappt?

Vielen Dank

**Comment by riconeitzel** [comment]
In welcher phtml Datei steht der Text denn?

**Comment by zlep** [comment]
Hi, müsste eigentlich aus der billing.phtml kommen:

<?php if ($this->customerHasAddresses()): ?>
    <li class="wide">
        <label for="billing-address-select"><?php echo $this->__('Select a billing address from your address book or enter a new address.') ?></label>
        <div class="input-box">
            <?php echo $this->getAddressesHtmlSelect('billing') ?>
        </div>
    </li>
<?php endif; ?>

**Comment by riconeitzel** [comment]
dann sollte in Deinem Theme eine translate.csv mit folgendem Inhalt funktionieren:
```"Select a billing address from your address book or enter a new address.","Wählen Sie eine Rechungsadresse aus Ihrem Adressbuch.```

Wenn Du im Entwicklermodus arbeitest, dann geht:
```"Mage_Checkout::Select a billing address from your address book or enter a new address.","Wählen Sie eine Rechungsadresse aus Ihrem Adressbuch.```

**Comment by zlep** [comment]
Super, danke dir. Der Mage_Checkout:: Block-Zusatz war es. Damit funktioniert es.
Nur aus Interesse: Woher wusstest du, dass es sich um diesen Block handelt? Im Entwicklermodus wurde mir dieser Blockname nicht angezeigt.

Gruß

**Comment by riconeitzel** [comment]
Das ist der Modulname … Da geht es um den Scope der Zeichenfolgen. Im Entwicklermodus wird nur übersetzt, was im richtigen Scope liegt. Im Nicht-Entwicklermodus spielt das keine Rolle. Schließt Du das Ticket bitte? :-) Danke!

**Comment by zlep** [comment]
Es funktioniert jedoch ausschließlich nur mit dem Zusatz, egal ob Entwicklermodus oder nicht.
Wie dem auch sei, danke :)
