### ISSUE TITLE
extension key error

### ISSUE THREAD

**Issue by ExiSnail** [riconeitzel/German_LocalePack_de_DE#244]
Hallo,
wir haben frisch magento 1.9 installiert und wollten das deutsche Sprachpaket installieren.
Aber über den Magento Connect manager nimmt der den extension key nicht an, den wir auf der magento Seite bekommen.

Fehlermeldung:
Could not resolve: magento-community (Domain name not found)

Ich finde leider das Paket auch nicht zum Herunterladen, um es manuell aufzuspielen.

Da wir gerne eine deutsche Magento-Oberfläche hätten, sind Tipps zu diesem Fehler herzlich angenommen.

**Comment by riconeitzel** [comment]
Hi,

Ihr müsst auf der Kommandozeile „mage init“ und/oder „mage setup“ (glaub ich wars) ausführen, damit er den Channel nicht als Domain erkennt.

Ansonsten einfach die Dateien von hier nehmen (bessere!! Option)

Viele Grüße, Rico

**Comment by ExiSnail** [comment]
Danke für die schnelle Antwort.

Wo finde ich die Dateien hier? Der Link direkt auf der Seite führt mich auf die Magentoseite, wo ich den Extension key generiert bekommen habe.

Ich finde mich hier auf der Seite leider nicht so gut zurechtn.

Liebe Grüße
Exi

**Comment by riconeitzel** [comment]
Rechts oben sollte ein DownlodButton sein, da bekommst du ein ZIP file

Liebe Grüße Rico

**Comment by noob999999999** [comment]
Hallo
Da es bei mir auch oben genannte Fehler eingeblendet wird und ich schon den ganzen Tag versuche zu instalieren würde ich auch gerne downladen. Jedoch finde ich den DownlaodButton nicht...

**Comment by Schrank** [comment]
https://github.com/riconeitzel/German_LocalePack_de_DE

<img width="1027" alt="bildschirmfoto 2017-09-10 um 17 06 52" src="https://user-images.githubusercontent.com/379680/30250202-96646378-964a-11e7-8bfe-617a33f43973.png">

**Comment by noob999999999** [comment]
Herzlichen Dank Schrank :)
Ich habe den Zip-Datei uploaded, jedoch erscheint folgende Fehlermeldung:
![fehlermeldung-1](https://user-images.githubusercontent.com/31823036/30250341-dd0dfcec-964c-11e7-8363-a876a03e6652.JPG)

**Comment by Schrank** [comment]
Schmeiß einfach alles in dein magento root. Magento Connect ist murks, damit kann man nicht ordentlich versionieren. Und ich hoffe du hast ein Testsystem :)

**Comment by Schrank** [comment]
Also in den Ordner wo app, var, js, etc. schon liegen

**Comment by noob999999999** [comment]
Ok. mache ich:) Danke dir,
ein Testsystem habe ich zwar keine. Ich versuche alles via direkt auf dem PleskPanel. Habe schon x mal instaliert und wieder deinstalliert.

**Comment by noob999999999** [comment]
Nachtrag: Ich habe alles in root geladen, wie kann ich das Sprachpaket aktivieren/installiieren?
Vielen Dank

**Comment by riconeitzel** [comment]
Bitte im Backend anmelden, system > configuration, general > localization 

Dort dann German (Germany) wählen und speichern.
