### ISSUE TITLE
Wie kann ich das deutsche Sprachpaket ( .zip von GitHub ) in meine Magento Installation integrieren?

### ISSUE THREAD

**Issue by Supermario72** [riconeitzel/German_LocalePack_de_DE#247]
Hallo zusammen.
Bin ein ziemlicher Anfänger und versuche grade seit Stunden im Netz eine Beschreibung zu finden, wie ich die .ZIPs von GitHub (beispielsweise das german language pack) in meine Magento 1.9.3.4 Installation integrieren kann.
Über den Connect Manager ist, wie man so liest, nicht so toll.
Deshalb würde ich das gern eleganter lösen...
Ich lese immer nur, die .zip runterladen und installieren...
ABER WIE?
Hoffe die Frage ist nicht allzu "dumm".
Ich bitte um Hilfe, ...hab schon graue Haare ;-)
Danke

**Comment by riconeitzel** [comment]
hi!

Einfach den Inhalt der ZIP in das Magento-Rootverzeichnis reinkopieren - fertig :-)

Liebe Grüße Rico

**Comment by Supermario72** [comment]
Hi.
Danke für die Hilfe.
Hab da noch ne kurze "Abschlussfrage"...
D.H. dann folglich, dass bei dem Reinkopieren, nur die Inhalte (sowohl Ordner als auch Dateien) hinzugefügt und wenn vorhanden, auch überschrieben werden, die schon vorhanden sind?!?
Wenn also z.B. der Ordner "app" 3 neue Unterverzeichnisse hat, der bestehende Ordner "app" aber beispielsweise 10 Unterverzeichnisse, dann werden nur die 3 hinzugefügt oder geändert... und nicht die restlichen 8 gelöscht...?!?

**Comment by Schrank** [comment]
Das kommt auf dein Betriebssystem an, Windows führt zusammen, auf Mac und Linux muss man ein wenig vorsichtig sein, ich benutze da immer `rsync` für. Aber bei der Frage vermute ich, dass du auf Windows unterwegs bist? (was nicht vorwurfsvoll gemeint ist, gute Frage!)

**Comment by Supermario72** [comment]
Also ich hatte vor, die Dateien über FileZilla in den Root der Installation zu schieben.
Windows...ja...
Das sollte doch dann so klappen, oder?
Muss ich noch was beachten bei der Magento 1.9.3.4 und dem aktuellen
German_LocalePack_de_DE   ???

**Comment by Schrank** [comment]
FileZilla sollte das auch tun, ja. Du solltest ein Test-System haben bevor du dir ein Live-System kaputt schießt. Ich empfehle ein Backup der Datenbank und der Dateien.

Ansonsten wenn du gerade dabei bist ein Update auf Magento 1.9.3.6 :)

**Comment by Supermario72** [comment]
OK...
Klar, ich teste auf einer Installation und sichere von Zeit zu Zeit die Dateien weg.
Muss leider grade den alten 1.6er Shop komplett neu aufsetzen und fange daher eh bei Null an...
Stimmt...die DB sollte ich dann immer mit sichern. Danke nochmal für den Tip!
Mache ich gleich.
Das Update auf Magento 1.9.3.6 ... vor oder nach dem Sprachpaket? ... und WIE spiele ich das Update am besten ein, wo wir grad dabei sind? ;-)

**Comment by Schrank** [comment]
Ich mache es so: http://blog.fabian-blechschmidt.de/magento-1-update/
Ich bin mir aber nicht sicher, ob der Weg auch für dich brauchbar ist.

**Comment by Supermario72** [comment]
Schau ich mir mal an.
Noch eine kurze Frage.
Ich habe mir die Anmerkungen von Rico durchgelesen und da Stand:
...

In Magento 1.9.0.x liefert der Hersteller bereits eine Übersetzung mit. Diese Übersetzung ist jedoch vollautomatisch erstellt worden und hat mit diesem Projekt hier nichts zu tun. Ab Magento 1.9.1.0 ist dies nicht mehr der Fall.

Leider lässt sich dadurch unser Sprachpaket nicht ohne Weiteres installieren. Es sind daher folgende Schritte auszuführen, bevor dieses Sprachpaket per Magento Connect installiert werden kann:

    Im Magento-Hauptverzeichnis in den Ordner *app/locale/ wechseln
    Dort den Ordner de_DE umbenennen in magento_de_DE

Anschließend dieses Sprachpaket installieren
...

Muss ich das auch beachten, bin nicht ganz schlau draus geworden ehrlich gesagt, ob sich das nur auf die 1.9.0.x bezieht, oder auch auf die nachfolgenden Versionen...

**Comment by Schrank** [comment]
Das ist meines Wissens nach mit der neuen Version wieder gefixt.

**Comment by Schrank** [comment]
kannst du also ignorieren

**Comment by Supermario72** [comment]
Super...
Also Deine Beschreibung ist echt gut und mir juckt es auch in den Fingern, mich mit GIT zu beschäftigen und damit zu arbeiten, weil es ja wohl damit anscheinend relativ einfach sein soll, die Versionen zu verwalten und auch wieder Dinge rückgängig zu machen, wenn etwas nicht läuft usw....Aaaber...
1. Hab ich dazu grade leider wenig Zeit und
2. hab ich die Befürchtung, dass es mich durch mein "geringes, angeeignetes Wissen" in dem Bereich, mich wohl noch VIEL mehr Zeit kosten würde... ;-)

**Comment by sreichel** [comment]
> Bin ein ziemlicher Anfänger ...

Wurscht, jeder fängt mal irgendwo an :)

Wie @Schrank schon empfielt, bissl einlesen in GIT, modman und Co und das Leben wird deutlich einfacher :)

> hab ich die Befürchtung, dass es mich durch mein "geringes, angeeignetes Wissen" in dem Bereich, mich wohl noch VIEL mehr Zeit kosten würde... ;-)

Nee! Denke der erste zeitsparende Schritt ist `modman`. Ein Aufruf über die Kommandozeile um Erweiterungen zu installieren/deinstallieren oder zu aktualisieren ... ohne das Reste im Dateisystem bleiben. Spart hinten raus sehr viel Zeit.

**Comment by Supermario72** [comment]
Noch ne kurze Frage hinterher.
Ich habe alle Dateien nach / kopiert.
Nun ist mir aber aufgefallen, dass ich ja sicher einige davon garnicht benötige, oder?!
Ich möchte natürlich den "root" schön sauber halten...
WAS wird dringend benötigt von den Dateien und Ordnern und was nicht???
DANKE euch vorab

**Comment by riconeitzel** [comment]
package/
MagentoConnect.html
README.md
composer.json
modman

kannst du auslassen

**Comment by Supermario72** [comment]
Hi.
Kurze Frage.
Häufig ist eine "package.xml bei den Extensions dabei.
Wofür benötige ich die?
Oder kann Sie auch weggelassen werden?

Danke

2017-10-12 13:59 GMT+02:00 Rico Neitzel <notifications@github.com>:

**Comment by riconeitzel** [comment]
Hi,

die kann in deinem Fall einfach weggelassen werden. Sie enthält Informationen über den Paketinhalt, aber du Installierst ja per ZIP-Datei. Da spielt das eh keine Rolle :-)

Viele Grüße
 Rico

**Comment by Supermario72** [comment]
Hallo Rico.

Mal wieder eine kleine Frage.
Ich möchte und muss an die Verkauftsemails die AGBs usw. als PDF im Anhang
der Emails anhängen.
Hast Du da einen Tip, wie das geht, oder eine Extension?

Danke Vorab!
Mario

**Comment by riconeitzel** [comment]
Hallo Mario,

https://www.vianetz.com/de/attachtermsandconditions.html

Viele Grüße
 Rico

Wenn Ihnen dieser Service geholfen hat, lassen Sie es mich wissen: http://tinyurl.com/ricohilft -- ;-)

**Comment by Schrank** [comment]
Imho reicht anhängen nicht, das muss als text in die mail 🙄 fragen Sie ihren Anwalt

**Comment by Supermario72** [comment]
Hallo Rico.

Danke für die wie immer schnelle Hilfe !!! ;-)
Ich schaue mir das mal an.

Du hast Recht.
BEIDES werde ich auch machen...
Die Texte von AGB und Widerruf in die Emails bringen ist aber einigermaßen
einfach, oder?
Dazu muß ich doch nur in die Email Vorlagen, am Ende zb. {{block
type="cms/block" block_id="mrg_revocation"}} einfügen...oder?!

**Comment by Schrank** [comment]
Genau, wobei du ggf über einen wechsel zu magesetup nachdenken willst. Das wird in Gegensatz zu mrg noch ein wenig weiterentwickelt

**Comment by Supermario72** [comment]
Habe magesetup schon installiert.
Werden damit denn die Texte automatisch angehängt UND auch die PDFs???
Bin noch in der Entwicklung und außerdem ein "Anfänger"... hab noch keine
Testbestellung gemacht und weiß daher noch nicht, wie die Mails aussehen,
die verschickt werden...

**Comment by riconeitzel** [comment]
Texte angehängt ja, PDFs nein – dafür braucht's eine Extension wie die oben genannte.

Wenn Ihnen dieser Service geholfen hat, lassen Sie es mich wissen: http://tinyurl.com/ricohilft -- ;-)

**Comment by Supermario72** [comment]
Guten morgen Rico.

Leider bekomme ich die Extension nicht ans laufen...
Die Dateien werden einfach nicht an die Mails angehängt. :-(
Vielleicht hast Du ja ne Idee?

Ein anderes unschönes Problem stört mich allerdings noch mehr.
Ich habe im Checkout, im letzen Schritt zwei "Fehler" (siehe Grafik weiter
unten)
1. eine Leerzeile, die den Rahmen mit den Infos "zerstört" und
2. möchte ich den Button an den rechten und nicht an den linken Rand
haben...
WIE bzw. WO muss ich nachschauen, um das zu ändern bzw. zu beheben?
[image: Inline-Bild 2]

Danke für Deine Hilfe!!!

Mario

Am 8. November 2017 um 14:44 schrieb Rico Neitzel <notifications@github.com>
:

**Comment by riconeitzel** [comment]
Hallo Mario,

diesen Supportumfang kann ich hier kostenfrei leider nicht geben, da ich weder deine Installation kenne, noch dieses Ticket der richtige Platz für diese Fragen ist. Wenn Du möchtest, kannst Du Dich gern per eMail an info@buro71a.de <mailto:info@buro71a.de> wenden, dort kann ich dir - kostenpflichtig - gerne bei Deinen Problemen helfen.

Viele Grüße
 Rico

**Comment by Supermario72** [comment]
Hallo Rico.

Vielen Dank.
Das hört sich gut an.

Ich sammel mal ein paar Dinge und vlt könnt Ihr mir dann vorab sagen, was
es kosten würde.
Das wäre gut!

Am 14. November 2017 um 08:52 schrieb Rico Neitzel <notifications@github.com

**Comment by Supermario72** [comment]
Hallo Rico.

Danke für den Tip mit VIANETZ... PDFs an Emails anhägen.

Kannst Du auch einen Tip geben, wie ich auf der Produktseite einen neuen
Reiter z.b. mit Datenblätter (PDFs) anlegen kann.
Ich verlasse mich am liebsten auf Empfehlungen, als zig Sachen selber
auszuprobieren...

Wäre super.
Vielen Dank im Voraus!
Mario

Am 7. Oktober 2017 um 19:09 schrieb Rico Neitzel <notifications@github.com>:

> hi!
>
> Einfach den Inhalt der ZIP in das Magento-Rootverzeichnis reinkopieren -
> fertig :-)
>
> Liebe Grüße Rico
>
>
>

**Comment by Supermario72** [comment]
Hallo Rico.

Eine kurze Anfängerfrage:

Ich habe die CE 1.9.3.6 installiert.
Hierzu gibt es mittlerweile ja zwei Updates. (1.9.3.7 und 1.9.3.8)

Reicht es zum Aktualisieren aus, die Dateien über FTP ins Verzeichnis zu
spielen?
Sollte zuerst das 1.9.3.7 und dann das 1.9.3.8 installiert werden?

Über eine Antwort wäre ich super dankbar!

Gruss
Mario


Am 7. Oktober 2017 um 19:09 schrieb Rico Neitzel <notifications@github.com>:

> hi!
>
> Einfach den Inhalt der ZIP in das Magento-Rootverzeichnis reinkopieren -
> fertig :-)
>
> Liebe Grüße Rico
>
>
>

**Comment by Schrank** [comment]
Hi @Supermario72 ich fürchte privaten Support leiten übersteigt ein wenig unsere Zeit. Wenn du mir eine Mail an github@fabian-blechschmidt.de schickst, lade ich dich gerne ins deutsche Magento Slack ein, da sind 238 Menschen, die gerne Fragen beantworten :-)
