### ISSUE TITLE
Kein Login zum connect manager mehr möglich

### ISSUE THREAD

**Issue by Supermario72** [riconeitzel/German_LocalePack_de_DE#248]
Hallo.
Nach der Installation kann ich mich leider nicht mehr im connect manager einloggen.
Die deutsche Übersetzung ist zwar da, aber wenn ich meine Login Daten eingebe und bestätige, passiert rein garnichts...

Bitte um Hilfe.
Danke

**Comment by riconeitzel** [comment]
Hat das vielleicht mit der gleichzeitigen Installation von magesetup zu tun?

**Comment by Supermario72** [comment]
Eigentlich nicht denke ich, das Phänomen hatte ich schon nach dem German_LocalPack...
Habe jetzt einfach mal vor die URL ein https:// gestellt und komme dann pötzlich rein...

**Comment by Supermario72** [comment]
Hallo...
Danke für die Antwort.
Wie geht es eigentlich, dass ich nur per Email antworten kann und nicht
über die Posts alles mit den primitiven Fragen voll mülle... ;-)

Also der Effekt war schon nach der Installation des Language Packs da...!
Wenn ich https:// vor die URL setze...dann gehts



Am 12. Oktober 2017 um 18:38 schrieb Rico Neitzel <notifications@github.com>
:

**Comment by riconeitzel** [comment]
Das hat nichts mit dem Sprachpaket zu tun. Da hast du irgendwo noch was anderes geändert.

Du müllst hier niemanden zu :-)

**Comment by riconeitzel** [comment]
Falls Du lokal arbeitest, Chrome und .dev als Domain nutzt, dann liegt das an Chrome. Ansonsten schau in der Tabelle core_config_data nach den Einträgen mit path LIKE '%base_url%' … da steht dann vermutlich https.
